version: '3'
services:
  node:
    container_name: node
    build:    
      context: ./app
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./app:/usr/src/app
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 

volumes:
  mysql-data:
